steps:
  # build the app
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/reservations/production',
      ]
  # auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/auth/production',
      ]
  # notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/notifications/production',
      ]
  # payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'australia-southeast2-docker.pkg.dev/copper-booster-374803/payments/production',
      ]
serviceAccount: 'projects/copper-booster-374803/serviceAccounts/131655006502-compute@developer.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
